name: Auto-Approve Master PRs
on:
  pull_request:
    types: [opened, reopened, synchronized]
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Approve PR
        run: echo Hello, world!
